wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/new_page/", views.new_page, name="new_page"),
    path("wiki/save_entry/", views.save_entry, name="save_entry"),
    path("wiki/<str:title>/", views.wiki_page, name="wiki_page"),
    path("wiki/random_page", views.random_page, name="random_page"),


]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import re
import random

from django import forms
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from . import util
from .util import get_entry

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="Content", widget=forms.Textarea)
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki_page(request, title):
    print("Title coming from post: ", title)
    if request.method == "GET":
        print("GET: ", title)
        title_content = get_entry(title)
        print("GET: Title Content: ", title_content)
        if not title_content:
            raise Http404("Page not Found")

        return render(request, "encyclopedia/title.html",
                      {"title": title,"title_content": title_content})

    elif request.method == "POST":
        title = request.POST.get("q")
        print("POST: ", title)
        title_content = get_entry(title)
        print("POST: Title Content: ", title_content)
        if not title_content:
            print("Am I here?")
            return entry(request, title)

        return HttpResponseRedirect(reverse("encyclopedia:wiki_page", args=[title]))


def entry(request, title):
    if request.method == "GET":
        print("GET: ENTRY: ", title)
        pass

    if request.method == "POST":
        print("POST: ENTRY: ", title)
        entries = util.find_matching_entry(title)
        print("Print en la entry de entries: ", entries)

        if entries:
            return render(request, "encyclopedia/index.html", {
            "entries": entries})
        else:
            return HttpResponseRedirect(reverse("encyclopedia:index"))


def new_page(request):
    return render(request, "encyclopedia/new_page.html",
                  {"new_entry": NewEntryForm()})


def save_entry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        print("YEAH, the form: ", form)
        title = form.cleaned_data["title"]
        if title in util.list_entries():
            raise Exception("Title Already Exists")

        title = request.POST.get("title")
        content = request.POST.get("content")

        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("encyclopedia:wiki_page", args=[title]))


def random_page(request):
    entries = util.list_entries()
    chosen = random.choice(entries)

    return HttpResponseRedirect(reverse("encyclopedia:wiki_page", args=[chosen]))

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:wiki_page' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                {% if title %}
                <form action="{% url 'encyclopedia:wiki_page' title %}" method="post">
                {% else %}
                <form action="{% url 'encyclopedia:wiki_page' 'dummy_title' %}" method="post">
                {% endif %}
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create Page
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:save_entry' %}" method="post">
        {% csrf_token %}
        {{ new_entry }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ title_content }}
{% endblock %}